version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: kafka-weather-monitoring-app
    depends_on:
      - db
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/weather_kafka_spring
      - SPRING_DATASOURCE_USERNAME=compose-rayanalkhelaiwi
      - SPRING_DATASOURCE_PASSWORD=test1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=rayanalkhelaiwi
      - POSTGRES_PASSWORD=test1

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "locations-weather:1:3"
    depends_on:
      - zookeeper # ? double check: will it reflect/duplicate with KAFKA_ZOOKEEPER_CONNECT?